[JENKINS-71414] Add DataboundConstructor and remove un-necessary owne…
jenkinsci/config-file-provider-plugin pull request #277
Opened 2023-06-08 02:33 UTC by Dohbedoh

…r overload

* Added DataboundConstructor to the `FolderConfigFileProperty`
* Added symbol `folderConfigFile` to the property descriptor
* Remove `owner` overload that is un-necessary 
* Deprecated constructor

### Testing done

* Spin up Jenkins
* Create a Folder
* Add Folder config files
* Save

--> Validate the the config files are still there after save
--> Validate the the config files are still there after restart

* create a pipeline job in the folder:

    ```
    node {
        configFileProvider([configFile(fileId: '<fileID>, targetLocation: 'test.txt', variable: 'TEST')]) {
          sh "cat $TEST"
        }
    }
    ```

* Run the pipeline

--> Validate that it properly injects the file and the content is expected

### Submitter checklist

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-06-08 08:06 UTC, alecharp commented
Would it be possible to test this automatically?

2023-06-13 15:27 UTC, rsandell commented on src/main/java/org/jenkinsci/plugins/configfiles/folder/FolderConfigFileProperty.java
> +    @Symbol("folderConfigFile")
```suggestion
    @Symbol("folderConfigFiles")
```

2023-06-13 15:28 UTC, rsandell commented
Last time I checked JCasC didn't support creating folders and other Items, so the title isn't really correct.

2023-06-15 08:43 UTC, jtnord commented on src/main/java/org/jenkinsci/plugins/configfiles/folder/FolderConfigFileProperty.java
>      /*package*/ FolderConfigFileProperty(AbstractFolder<?> owner) {
given this is package-private scope - should all references not be be updated and this removed rather then leaving deprecated as they are only in this code.

2023-06-27 15:20 UTC, rsandell approved these changes

2023-06-29 15:23 UTC, rsandell requested changes
Still approved just don't merge this yet.

2023-07-11 10:11 UTC, rsandell approved these changes

2023-07-11 10:12 UTC, merged